# Continuous Integration (CI) is the practice, in software
# engineering, of merging all developer working copies with a shared mainline
# several times a day < https://docs.platformio.org/page/ci/index.html >
#
# Documentation:
#
# * Travis CI Embedded Builds with PlatformIO
#   < https://docs.travis-ci.com/user/integration/platformio/ >
#
# * PlatformIO integration with Travis CI
#   < https://docs.platformio.org/page/ci/travis.html >
#
# * User Guide for `platformio ci` command
#   < https://docs.platformio.org/page/userguide/cmd_ci.html >
#
#
# Please choose one of the following templates (proposed below) and uncomment
# it (remove "# " before each line) or use own configuration according to the
# Travis CI documentation (see above).
#


#
# Template #1: General project. Test it using existing `platformio.ini`.
#

language: python
python:
    - "3.7"

sudo: false

install:
    - pip install -U pyinstaller
    - pip install -r requirements.txt

script:
    - pyinstaller -F IRbaby-tool.py

before_deploy:
- git config --global user.name "Caffreyfans"
- git config --global user.email "Caffreyfans@163.com"
- export RELEASE_FILE=./dist/$(ls dist)
- git tag 0.1.4

deploy:
  provider: releases
  file_glob: true
  api_key:
    secure: B/Kelw4E5G1INKKDJurNqJLWnwVDjl96848C8DBIXQaUark5nuYzPLO1gNimFpYDgPrJDiZXyRDUVdUBVA2h1SR09Qz49ECelwt1gj0RdJvt/eIqjAQM8nkXMQf7h5krzT9u++22lqKvWMgH12M0swWX9ARkwvxZbFxulAjBw1kU23ofwsl3K1P3LcLOV2Rr5hfXgRudJzjgC0HeZjXOQV0CzDXwGsfTlxPfsxgREUZeHrYeJvIvehcDTCphbaW+UaNgXDZU8sgth4igSbEUwGtIWxSlWp7RcO11iTdd4uDvc/EqZaCoBwYGSZ4MzFiq3NwtE1GARrbK1aoua5kqi9ADq7mY2MZDe9yfZd+Jr0jbmgLe9INSBZDmlW5eVZi0wDqiuFv0/gfE+1MR8EuJUw1PiEOetWfDHYFplz0pPoPFaElq+nPSpBagT3x4RG8ZRRofz4Zf8CpFLvSZBQnZWxFqEv5403IXwSoKKvWpjaDYThyQMDmYRUcJcZqRH7lag9yHavuTELu0NUHXmSwOp1/PamWJV+6qticurvDSLaSmK+hgjXpCyj9gAvQcL9cdMvrZTyRfHKHLQPbUk3L8BfB3D7A1/XitmW+vTILtqFaeaYAWf+1PJFFeBry9/QhZNIUeD4YWlvc0Mc5hZyZ+Jg4+anhdhZ6aq3YNu/rT9u4=
  file: "${RELEASE_FILE}"
  skip_cleanup: true
  # on:
  #   tags: true
#
# Template #2: The project is intended to be used as a library with examples.
#

# language: python
# python:
#     - "2.7"
#
# sudo: false
# cache:
#     directories:
#         - "~/.platformio"
#
# env:
#     - PLATFORMIO_CI_SRC=path/to/test/file.c
#     - PLATFORMIO_CI_SRC=examples/file.ino
#     - PLATFORMIO_CI_SRC=path/to/test/directory
#
# install:
#     - pip install -U platformio
#     - platformio update
#
# script:
#     - platformio ci --lib="." --board=ID_1 --board=ID_2 --board=ID_N
